version: '3.5'
services:
  app:
    build:
      context: '.'
    env_file: '.env'
    ports:
      - '8080:8080'
    volumes:
      - '.:/opt/project/app:delegated'
    entrypoint: '/opt/project/app/docker/entrypoint.sh'
    command: '/opt/project/app/docker/command.sh'
    networks:
      manager-dev:
        aliases:
          - 'app.dev'
networks:
  manager-dev:
    name: 'manager-dev'
    
